function(add_my_executable target source)
    add_executable(${target} ${source})
    target_include_directories(${target} PRIVATE ${MGARDx_INCLUDES} ${SZ3_INCLUDES} ${ZSTD_INCLUDES} ${QoZ_INCLUDE_DIR} ${MGARD_INCLUDE_DIR})
    target_link_libraries(${target} ${PROJECT_NAME} ${SZ3_LIB} ${ZSTD_LIB} ${MGARD_LIBRARY})
endfunction()

add_my_executable(test_mdr_refactor test_mdr_refactor.cpp)
add_my_executable(test_mdr_reconstructor test_mdr_reconstructor.cpp)
add_my_executable(test_pdr_refactor test_pdr_refactor.cpp)
add_my_executable(test_pdr_reconstructor test_pdr_reconstructor.cpp)
add_my_executable(test_pdr_delta_refactor test_pdr_delta_refactor.cpp)
add_my_executable(test_pdr_delta_reconstructor test_pdr_delta_reconstructor.cpp)
add_my_executable(refactor_d64 refactor_d64.cpp)
add_my_executable(qoi_Vtot_d64 qoi_Vtot_d64.cpp)
add_my_executable(two_modes_refactor two_modes_refactor.cpp)
add_my_executable(two_modes_reconstructor two_modes_reconstructor.cpp)
